// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String APIKEY = String.fromEnvironment('FLUTTER_API_KEY');
  static const String APIID = String.fromEnvironment('FLUTTER_APP_ID');
  static const String SENDERID = String.fromEnvironment('FLUTTER_SENDER_ID');
  static const String PROJID = String.fromEnvironment('FLUTTER_PROJ_ID');
  static const String STORAGEBUCKET = String.fromEnvironment(
    'FLUTTER_STORAGE_BUCKER',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: APIKEY,
    appId: APIID,
    messagingSenderId: SENDERID,
    projectId: PROJID,
    authDomain: 'fir-auth-19b9d.firebaseapp.com',
    storageBucket: STORAGEBUCKET,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRBod3Kn5_XxnEYjWaHoTgzYQ6eEz_HQ',
    appId: APIID,
    messagingSenderId: SENDERID,
    projectId: PROJID,
    storageBucket: STORAGEBUCKET,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZgF4CVHEXNMoiJ1EHCNzLiownCrQRbc',
    appId: APIID,
    messagingSenderId: SENDERID,
    projectId: PROJID,
    storageBucket: STORAGEBUCKET,
    iosClientId:
        '231792409456-cs5m2lgcdhsqmn9mtp17pbdsjg1lhr01.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZgF4CVHEXNMoiJ1EHCNzLiownCrQRbc',
    appId: APIID,
    messagingSenderId: SENDERID,
    projectId: PROJID,
    storageBucket: STORAGEBUCKET,
    iosClientId:
        '231792409456-cs5m2lgcdhsqmn9mtp17pbdsjg1lhr01.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd_V1owBZHFDgzFYIxGtFjinEwBKYP-Rw',
    appId: APIID,
    messagingSenderId: SENDERID,
    projectId: PROJID,
    authDomain: 'fir-auth-19b9d.firebaseapp.com',
    storageBucket: STORAGEBUCKET,
  );
}
