// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2bsJRp-0sWgI2XPQC0UOM70NxZEbEMDM',
    appId: '1:231792409456:web:cbc3f6063b0bde48536db5',
    messagingSenderId: '231792409456',
    projectId: 'fir-auth-19b9d',
    authDomain: 'fir-auth-19b9d.firebaseapp.com',
    storageBucket: 'fir-auth-19b9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRBod3Kn5_XxnEYjWaHoTgzYQ6eEz_HQ',
    appId: '1:231792409456:android:cf183a5ec1e31933536db5',
    messagingSenderId: '231792409456',
    projectId: 'fir-auth-19b9d',
    storageBucket: 'fir-auth-19b9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZgF4CVHEXNMoiJ1EHCNzLiownCrQRbc',
    appId: '1:231792409456:ios:4ebaa388e021227a536db5',
    messagingSenderId: '231792409456',
    projectId: 'fir-auth-19b9d',
    storageBucket: 'fir-auth-19b9d.appspot.com',
    iosClientId: '231792409456-cs5m2lgcdhsqmn9mtp17pbdsjg1lhr01.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZgF4CVHEXNMoiJ1EHCNzLiownCrQRbc',
    appId: '1:231792409456:ios:4ebaa388e021227a536db5',
    messagingSenderId: '231792409456',
    projectId: 'fir-auth-19b9d',
    storageBucket: 'fir-auth-19b9d.appspot.com',
    iosClientId: '231792409456-cs5m2lgcdhsqmn9mtp17pbdsjg1lhr01.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd_V1owBZHFDgzFYIxGtFjinEwBKYP-Rw',
    appId: '1:231792409456:web:c337089641a69d59536db5',
    messagingSenderId: '231792409456',
    projectId: 'fir-auth-19b9d',
    authDomain: 'fir-auth-19b9d.firebaseapp.com',
    storageBucket: 'fir-auth-19b9d.appspot.com',
  );
}
